# Generated by Django 5.2.5 on 2025-08-22 19:35

import gallery.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-date_created'], 'verbose_name': 'Album', 'verbose_name_plural': 'Albumy'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-date_created'], 'verbose_name': 'Zdjęcie', 'verbose_name_plural': 'Zdjęcia'},
        ),
        migrations.AddField(
            model_name='photo',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='large',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(bucket_name='album.grzelka.pro-public', querystring_auth=False), upload_to=gallery.models.image_upload_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='original_image',
            field=models.ImageField(upload_to=gallery.models.image_upload_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(bucket_name='album.grzelka.pro-public', querystring_auth=False), upload_to=gallery.models.image_upload_to),
        ),
    ]
